version: '3.8'

services:
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "4000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./services/auth-service/.env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    volumes:
    - ./services/auth-service:/app
    - /app/node_modules
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - ./config/auth.env
      - ./config/posts.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  posts-service:
    build: ./services/posts-service
    container_name: posts-service
    ports:
      - "5000:3000"
    depends_on:
      - postgres
    env_file:
      - ./services/posts-service/.env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    volumes:
      - ./services/posts-service:/app
      - /app/node_modules
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d 
    depends_on:
      - auth-service
      - posts-service
    networks:
      - app-network

  notifications-service:
    build: ./services/notifications-service
    container_name: notifications-service
    ports:
      - "6000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./services/notifications-service/.env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    volumes:
    - ./services/notifications-service:/app
    - /app/node_modules
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
  redisdata:
